### ISSUE TITLE
Ошибка при запуске docker-compose

### ISSUE THREAD

**Issue by el-hombre0** [Iking007/SiPI#11]
При запуске отдельно контейнера с БД и .jar работает норм, но одновременно выдает ошибку:
` org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connection`

Вот docker-compose.yml, добавил healthcheck, проверяет, доступна ли БД для подключения, но почему-то на ошибку это не влияет.

```
version: "3.9"
services:
  java:
    build: ./docker/java
    container_name: java
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

  database:
    image: postgres:alpine3.17
    container_name: database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rootuser"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
```
